//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualCardEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardEffect
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EffectText { get; set; }
        public int EffectTrigger { get; set; }
        public int TriggerPlural { get; set; }
        public int TriggerOwner { get; set; }
        public int TriggerType { get; set; }
        public int EffectTarget { get; set; }
        public int TargetPlural { get; set; }
        public int TargetOwner { get; set; }
        public int TargetType { get; set; }
        public int FireCondition { get; set; }
        public int ConditionValue { get; set; }
        public int Effect { get; set; }
        public int Value1 { get; set; }
        public int Value2 { get; set; }
        public int Duration { get; set; }
        public int Cost { get; set; }
        public int DiscardCount { get; set; }
        public int DiscardType { get; set; }
        public int SacrificeCount { get; set; }
        public int SacrificeType { get; set; }
        public int Deplete { get; set; }
    }
}
