//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualCardEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FlavorText { get; set; }
        public int Cost { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public Nullable<int> CardLevel { get; set; }
        public string Notes { get; set; }
        public int Speed { get; set; }
        public int Reach { get; set; }
        public string Version { get; set; }
        public int DiscardCount { get; set; }
        public int DiscardType { get; set; }
        public int SacrificeCount { get; set; }
        public int SacrificeType { get; set; }
    }
}
