//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualCardEditor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChampionsDB : DbContext
    {
        public ChampionsDB()
            : base("name=ChampionsDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardEffect> CardEffects { get; set; }
        public virtual DbSet<CardEffectsJoin> CardEffectsJoins { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<CardTypesJoin> CardTypesJoins { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Effect> Effects { get; set; }
        public virtual DbSet<EffectTrigger> EffectTriggers { get; set; }
    }
}
